### ISSUE TITLE
Pepper URDF

### ISSUE THREAD

**Issue by michtesar** [OTL/urdf-viz#18]
Hi, I am having struggles to load Pepper robot URDF. I see from your images in docs you have used a Pepper robot. Are you please able to share URDF with me? Thank you.

**Comment by OTL** [comment]
Have you downloaded `pepper_meshes` package?

https://github.com/ros-naoqi/pepper_meshes/

It is separated from `pepper_description` because of license.

**Comment by michtesar** [comment]
I put them together but somehow self collision does not work anymore
