### ISSUE TITLE
Get method works but set method does not seem to work

### ISSUE THREAD

**Issue by prajval10** [OTL/urdf-viz#25]
Hi Takashi,

Thanks for the easy to use and open source urdf visualization application! 
 
I have a bug and probably its a fault on my end but I got the `/get_joint_positions` method to work and I can visualise it in the browser : 
![Screenshot from 2019-07-06 10-57-13](https://user-images.githubusercontent.com/22452731/60754116-d663d880-9fdc-11e9-930e-243967bfc168.png)

However, the set method gives the following error:
```
~$ curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"names": ["Joint_1", "Joint_2", "Joint_3", "Joint_4", "Joint_5", "Joint_6", "Joint_7"], "positions": [ 0.0, −0.5236, 0.0, −1.0472, 0.0, −1.0472, 0.0]}'  http://127.0.0.1:7777/set_joint_positions | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258  100   101  100   157    98k   153k --:--:-- --:--:-- --:--:--  251k
{
  "description": "error while parsing the JSON body",
  "cause": {
    "description": "JSON error",
    "cause": null
  }
}
~$ {
>   "is_ok": true,
>   "reason": ""
> 
> 
```

The urdf file is running in another terminal using `urdf-viz <path-to-file>.urdf` command and it works fine.

**Comment by OTL** [comment]
I copied your code, and sent it to jq, and it failed. It seems that your json is broken.

```
'{"names": ["Joint_1", "Joint_2", "Joint_3", "Joint_4", "Joint_5", "Joint_6", "Joint_7"], "positions": [ 0.0, −0.5236, 0.0, −1.0472, 0.0, −1.0472, 0.0]}'
```

I replaced your `−` with `-`, it worked.
I don't know about your keyboard, but it is similar to minus, but is not. 

https://www.fileformat.info/info/unicode/char/2212/index.htm

Please use ascii code instead of unicode(−).

**Comment by prajval10** [comment]
Ah, classical copy-paste error. Thanks, it works like a charm! 
Closing the issue!
