### ISSUE TITLE
Scale parameter for the stl mesh does not work

### ISSUE THREAD

**Issue by ags-dy** [OTL/urdf-viz#6]
If the scale of the visual model stl is set the program crashes:

`thread 'main' panicked at 'called Result::unwrap() on an Err value: Xml(failed to parse float array in 0.001)', libcore/result.rs:945:5
note: Run with 'RUST_BACKTRACE=1' for a backtrace.
`

example xml that causes the crash:

`
 <visual >
   <geometry >
    <mesh  scale="0.001" filename="visual.stl" />
   </geometry>
  </visual>
`

The same urdf file loads correctly in pybullet (with the correct scale).

Thanks,
Austin

**Comment by OTL** [comment]
I think scale must be vector, like scale="1 1 1" in urdf. pybullet is not correct.
But basically urdf format is not clear. It might be good idea to support your style scale.

http://wiki.ros.org/urdf/XML/link

Thank you for your feedback.

if your urdf is open, please let me know.
if not, don't mind.

**Comment by ags-dy** [comment]
Ah sorry, I should have checked the spec first.   You are right about it needing to be a vector, it all works now.

Thanks,
Austin

**Comment by OTL** [comment]
Good luck.
